### ISSUE TITLE
Under development?

### ISSUE THREAD

**Issue by monossido** [Assembless/gather-town-assembless-api#1]
Is this usable and under development?

I've succeded to get it working even without documentations
(the most difficolut parts was to understand wich is my gather space id, map id and to understand wich scopes include in user slack token)
But it doesn't recognize the gather members, we are all guests.
Plus the button "Visit Office" goes to https://app.gather.town/app/c0ajLLNc3ph92hRG/Assembless
![gnome-shell-screenshot-dxh8ww](https://user-images.githubusercontent.com/641268/166887650-a0f06798-8851-47f6-91e5-e5b867c4fc0d.png)

**Comment by DRFR0ST** [comment]
Hey! 
Thanks for trying out the app and sorry, we've been too busy lately to invest time into this. The app was built strictly to fulfill our needs here at Assembless, but we decided to open source it, of course. We are adding features on the go, but in fact the documentation and instructions are missing. We will deliver a configuration generator or an installer ASAP. The Slack scopes required to run the app will be provided soon too.

The members list is for now hardcoded and needs to be configured before building the app.
The structure should look somewhat like this:
```
const MEMBERS: Member[] = [
  {
    name: "DISPLAY NAME",
    slackId: "SLACK USER ID", // Read more => https://www.workast.com/help/articles/61000165203/
    gatherId: "GATHER PLAYER ID", // See explanation below.
  },
  ...
];
```
To get the Gather Player ID, you can now execute the `/gatherplayers` command in Slack (in the bots channel) to get a list of online players including their IDs. Make sure to pull the changes from this repo and add the `/gatherplayers` command in Slack bot panel.

Members configuration can be found here:
https://github.com/Assembless/gather-town-x-slack/blob/65911f3a0a31e8273cfba8a2977e8b6367ce8be2/src/config.ts#L11-L37

I hope this helped and in case you have more questions or trouble using the app, please let me know.

**Comment by DRFR0ST** [comment]
I can share with you the Slack bot configuration (it's a bit messy, but hey, it works! 😄)

### Event Subscriptions
![event subscriptions](https://user-images.githubusercontent.com/7634871/166986922-9815773f-0f36-46c6-84b4-cdf77fa497f2.png)

### Slash Commands
![slash commands](https://user-images.githubusercontent.com/7634871/166987582-0180c1cc-0153-4793-8030-5931d883e770.png)

I think the **Socket Mode** should be enabled.

Here's the **App Manifest**
```yaml
display_information:
  name: Gather Town
  description: An integration for Gather Town Assembless space.
  background_color: "#000000"
features:
  app_home:
    home_tab_enabled: true
    messages_tab_enabled: false
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: Gather Town
    always_online: false
  slash_commands:
    - command: /shakeit
      description: Shakes everybody's screen in Gather
      should_escape: false
    - command: /gatherplayers
      description: List online Gather players.
      should_escape: true
oauth_config:
  scopes:
    user:
      - channels:read
      - users:read
    bot:
      - app_mentions:read
      - channels:history
      - channels:join
      - channels:manage
      - channels:read
      - chat:write
      - chat:write.customize
      - chat:write.public
      - commands
      - emoji:read
      - users:read
      - users:write
settings:
  event_subscriptions:
    user_events:
      - user_change
    bot_events:
      - app_home_opened
      - app_mention
      - message.channels
      - user_change
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
```
